### ISSUE TITLE
Inaccuracy in Common Values section of UG

### ISSUE THREAD

**Issue by ylyma** [ylyma/pe#14]
![image.png](https://raw.githubusercontent.com/ylyma/pe/main/files/c331f415-caf1-4c4f-8a4b-c6816223ea87.png)

While this table states that 'n/' is for names like John Doe, it is also used for assignment names for the 'assign' input. It might be clearer to include that as an example under the same row, or as a new row.

**Comment by nus-pe-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
Initially, we used Student Names but we did take into consideration that this can be include different names hence we decided to change it to Names instead to be universal. 

In general, a flaw (e.g., a missing feature, a suboptimal design of a feature, a known bug) can be considered NotInScope if rectifying it is less important (based on the value/effort considerations) than the work that has been done already (because it is fine to delay lower priority work until future iterations

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.NotInScope`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

<catcher-end-of-segment><hr>
